image: mcr.microsoft.com/dotnet/sdk:8.0

tasks:
  - name: Setup Environment
    init: |
      export LT_USERNAME=sumeet_pal
      export LT_ACCESS_KEY=hD5T3Y76XOujSdIHQmYsyuco3OviJHTYdYq6cHHfFFfLOyFix9
      export LT_TUNNEL=false
      export LT_BUILD=LambdatestBuild
    command: |
      dotnet restore
      dotnet test

vscode:
  extensions:
    - ms-dotnettools.csharp
